# Site settings
title: Lava 
email: cha452jg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrod.github.io" # the base hostname & protocol for your site
github_username: astrod
permalink: pretty

# other links
facebook_username: chaejongun
github_username:  astrod
email: cha452jg@gmail.com

description_footer : "웹 개발에 대한 블로그입니다."

# comments
# two ways to comment, only choose one, and use your own short name
disqus_shortname: astrod

google_analytics_id: UA-76209577-1

# Build settings
markdown: kramdown
rdiscount:
    extensions:
      - generate_toc

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 2 
