# Site settings
title: Lava 
email: cha452jg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astrod.github.io" # the base hostname & protocol for your site
github_username: astrod

# Build settings
markdown: rdiscount
rdiscount:
    extensions:
      - generate_toc